# We're just using a "stubbed out" Travis right now so we can
# use Homu <https://github.com/barosl/homu> to auto-squash
# etc.
# (Stub change for testing)
language: c
dist: trusty
addons:
  apt:
    packages:
      - automake
      - autotools-dev
      - libcap-dev
script:
  - env NOCONFIGURE=1 ./autogen.sh

notifications:
  # This is Colin's instance of Homu, in the future
  # we'll move this to a production cluster.
  webhooks: http://escher.verbum.org:54856/travis
  email: false

branches:
  only:
    - auto

